namespace: WackoPicko
output:
  file_path: ./Fluid-Attacks-Results.csv
  format: CSV
working_dir: .
language: EN
apk:
  include:
    - glob(**/*.apk)
strict: true
sast:
  include:
    - .
sca:
  include:
    - .
  exclude:
    - glob(**/test/**)
output:
  file_path: test.csv
  format: CSV
