# .github/workflows/dev.yml
name: Standalone CLI
on: [push, pull_request]
jobs:
   machineStandalone:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
         - uses: docker://docker.io/fluidattacks/cli:latest
           name: machineStandalone2
           with:
             args: skims scan ./config/config.yaml
         - name: resultados
           uses: actions/upload-artifact@v4
           if: always()
           with:
             name: resultados
             path: Fluid-Attacks-Results.csv
            
      
            
